# RustyGPT configuration template (TOML)
# Copy to `config.toml` and update values for your environment.

profile = "dev"

[logging]
level = "debug"
format = "text"

[server]
host = "127.0.0.1"
port = 8080
public_base_url = "http://localhost:8080"

[server.cors]
allowed_origins = ["http://localhost:3000", "http://127.0.0.1:3000"]
allow_credentials = false
max_age_seconds = 600

[security.hsts]
enabled = false
max_age_seconds = 63072000
include_subdomains = true
preload = false

[security.cookie]
domain = ""
secure = false
same_site = "lax"

[security.csrf]
cookie_name = "CSRF-TOKEN"
header_name = "X-CSRF-TOKEN"
enabled = true

[rate_limits]
auth_login_per_ip_per_min = 10
default_rps = 50.0
burst = 100

[session]
ttl_seconds = 1209600
session_cookie_name = "SESSION_ID"
csrf_cookie_name = "CSRF-TOKEN"

[oauth]
redirect_base = "http://localhost:8080/api/auth/github/callback"

[oauth.github]
client_id = ""
client_secret = ""

[db]
url = "postgres://tinroof:rusty@localhost/rustygpt_dev"
statement_timeout_ms = 5000
max_connections = 10
bootstrap_path = "../scripts/pg"

[sse]
heartbeat_seconds = 20
channel_capacity = 128
id_prefix = "evt_"

[features]
auth_v1 = false
well_known = false
sse_v1 = false

[cli]
session_store = "~/.config/rustygpt/session.json"

[web]
static_dir = "../rustygpt-web/dist"
spa_index = "../rustygpt-web/dist/index.html"

[[well_known.entries]]
path = ".well-known/security.txt"
content_type = "text/plain"
body = """Contact: mailto:security@example.com
Expires: 2025-01-01T00:00:00Z
"""
