name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  LANG: en_US.UTF-8

jobs:
  build:
    name: Build and Test
    container:
      image: rust:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prep OS
        run: |
          apt-get update && apt-get install -y jq

      - name: Create .env file
        run: |
          cp .env.template .env

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Tools
        run: |
          rustup target add wasm32-unknown-unknown
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall trunk wasm-bindgen-cli wasm-opt sqlx-cli -y

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building with PATH=$PATH"
          trunk build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist/
          retention-days: 7
