name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
          rustup component add rustfmt clippy
          rustup target add wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Create .env file
        run: |
          cp .env.template .env

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build frontend
        run: |
          cd frontend
          trunk build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist/
          retention-days: 7
