name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rusty_gpt
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
          rustup component add rustfmt clippy
          rustup target add wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Create .env file
        run: |
          cp .env.template .env
          echo "GITHUB_CLIENT_ID=test_client_id" >> .env
          echo "GITHUB_CLIENT_SECRET=test_client_secret" >> .env
          echo "APPLE_CLIENT_ID=test_client_id" >> .env
          echo "DATABASE_URL=postgres://postgres:postgres@localhost/rusty_gpt" >> .env

      - name: Initialize database schema
        run: |
          export PGPASSWORD=postgres
          psql -h localhost -U postgres -d rusty_gpt -f .data/postgres-init/01-init-schema.sql
          psql -h localhost -U postgres -d rusty_gpt -f .data/postgres-init/02-stored-procedures.sql
          psql -h localhost -U postgres -d rusty_gpt -f .data/postgres-init/03-seed-data.sql

      - name: Install SQLx CLI and prepare query cache
        run: |
          cargo install sqlx-cli --no-default-features --features postgres
          export $(grep DATABASE_URL .env)
          cargo sqlx prepare

      - name: Build
        env:
          SQLX_OFFLINE: true
        run: cargo build --verbose

      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --verbose

      - name: Build frontend
        run: |
          cd frontend
          trunk build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist/
          retention-days: 7
