name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  SQLX_OFFLINE: true
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.template .env

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli sqlx-cli

      - name: Generate documentation
        run: |
          # Generate documentation for all crates
          cargo doc --no-deps --workspace

          # Copy the generated docs to the docs directory
          mkdir -p docs/api
          cp -r target/doc/* docs/api/

          # Ensure the index.html file exists
          touch docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
