name: docs

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency: docs-${{ github.ref }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install documentation tooling
        run: just install-docs

      - name: Build docs
        run: just docs-build

      - name: Generate LLM manifests
        run: just docs-index

      - name: Guardrails
        run: |
          ! grep -R --include='*.md' -E '(AKIA[0-9A-Z]{16}|SECRET_KEY|token=|password=|x-api-key)' docs || (echo "Secret-like pattern found" && exit 1)
          ! git ls-files docs | grep -E '\.(py|ipynb|html)$' && echo "OK" || (echo "Forbidden file type present" && exit 1)

      - name: Link check (optional)
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          cargo install --locked lychee
          lychee --verbose --no-progress docs || true

      - name: Package gh-pages assets
        run: |
          out_dir=$(mktemp -d)
          rsync -a book/ "$out_dir"/
          mkdir -p "$out_dir"/llm
          rsync -a docs/llm/ "$out_dir"/llm/
          touch "$out_dir"/.nojekyll
          echo "OUT_DIR=$out_dir" >> $GITHUB_ENV

      - name: Publish to gh-pages
        env:
          OUT_DIR: ${{ env.OUT_DIR }}
        run: |
          set -e
          git config user.name "ci"
          git config user.email "ci@users.noreply.github.com"
          git fetch origin gh-pages || true
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
            git reset --hard origin/gh-pages
          else
            git checkout -b gh-pages
          fi
          git ls-files -z | xargs -0 --no-run-if-empty git rm -f
          git clean -fdx
          cp -r "${OUT_DIR}/." .
          git add .
          git commit -m "docs: deploy ${GITHUB_SHA}" || echo "No changes to commit"
          git push origin gh-pages
          rm -rf "${OUT_DIR}"
