name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US

jobs:
  build:
    name: Build Documentation
    container:
      image: rust:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.template .env

      - name: Cache Cargo registries and git checkouts
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/cargo/git
            /usr/local/cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo installed binaries
        uses: actions/cache@v4
        with:
          path: /usr/local/cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Cargo Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked --jobs "$(nproc)" wasm-bindgen-cli sqlx-cli

      - name: Generate documentation
        run: |
          # Generate documentation for all crates
          cargo doc --no-deps --workspace

          # Copy the generated docs to the docs directory
          mkdir -p docs/api
          cp -r target/doc/* docs/api/

          # Ensure the index.html file exists
          touch docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
