name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
          rustup component add clippy
          rustup target add wasm32-unknown-unknown

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy check
        run: |
          cargo clippy --all-features -- -D warnings

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
          rustup component add rustfmt

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

  audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: |
          cargo generate-lockfile
          cargo audit --json || true
          echo "Security audit completed. Check the output for any vulnerabilities."
          echo "Note: Currently there's a vulnerability in the 'rsa' crate (RUSTSEC-2023-0071) and"
          echo "unmaintained packages 'paste' and 'proc-macro-error' that should be addressed."
