name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  LANG: en_US.UTF-8
  CARGO_HOME: ${{ github.workspace }}/.cargo

jobs:
  build:
    name: Build Release
    container:
      image: rust:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Cargo registries and git checkouts
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/cargo/bin
            /usr/local/cargo/git
            /usr/local/cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo installed binaries
        uses: actions/cache@v3
        with:
          path: /usr/local/cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Prep OS
        run: apt-get update && apt-get install -y jq

      - name: Create .env file
        run: cp .env.template .env

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Cargo Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked --jobs "$(nproc)" trunk wasm-bindgen-cli wasm-opt sqlx-cli

      - name: Build
        run: cargo build --release

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Trunk might be at $(which trunk)"
          TRUNK_DIR=${{ env.CARGO_HOME }}/bin
          TRUNK_DIR=$(realpath $TRUNK_DIR)
          echo "Running trunk from $TRUNK_DIR"
          $TRUNK_DIR/trunk build --release

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%h)" $(git rev-list --max-parents=0 HEAD)..HEAD >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..HEAD >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this Release

            ${{ env.CHANGELOG }}

            ## Installation

            Download the appropriate binary for your platform and follow the installation instructions in the [README](README.md).
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          files: |
            target/release/backend
            frontend/dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          DATE=$(date +%Y-%m-%d)

          # Create new changelog entry
          echo -e "# Changelog\n\n## $VERSION - $DATE\n\n${{ env.CHANGELOG }}\n\n$(cat CHANGELOG.md 2>/dev/null || echo '')" > CHANGELOG.md

          # Commit and push the updated CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for $VERSION [skip ci]"
          git push --force-with-lease --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
